/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Empleados;
import Clases.Proveedores;
import Utilidades.Empleado_Utilidades;
import Utilidades.Proveedor_Utilidades;
import Utilidades.vld_textbox;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Frm_Proveedor extends javax.swing.JFrame {

    public Frm_Proveedor() {
        initComponents();
        Disable();
        tabla();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nuev = new javax.swing.JButton();
        guarda = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtempresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsitio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdes = new javax.swing.JTextField();
        txtprod = new javax.swing.JTextField();
        txtdirec = new javax.swing.JTextField();
        txtele = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txte = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_prov = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        date_fecha = new com.toedter.calendar.JDateChooser();
        modificar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Niagara Solid", 1, 48)); // NOI18N
        jLabel2.setText("Nuevo proveedor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 240, -1));

        nuev.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        nuev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        nuev.setText("Nuevo");
        nuev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevActionPerformed(evt);
            }
        });
        getContentPane().add(nuev, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 100, 50));

        guarda.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        guarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_over.png"))); // NOI18N
        guarda.setText("Guardar");
        guarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardaActionPerformed(evt);
            }
        });
        getContentPane().add(guarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 110, 50));

        eliminar.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        eliminar.setText("Cancelar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 120, 50));

        salir.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1487472258_Exit.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 50, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1487471876_mypc_save.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 120, 120));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel4.setText("Código");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(10, 10, 41, 26);
        jLayeredPane1.add(txtcode);
        txtcode.setBounds(80, 10, 250, 20);

        jLabel5.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel5.setText("Empresa");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(10, 50, 60, 20);
        jLayeredPane1.add(txtempresa);
        txtempresa.setBounds(80, 50, 250, 20);

        jLabel7.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel7.setText("Sitio web");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(10, 250, 60, 20);

        jLabel9.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel9.setText("Dirección");
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(10, 90, 70, 20);

        jLabel10.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel10.setText("Teléfono");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(10, 130, 60, 20);

        jLabel11.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel11.setText("Celular");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(10, 170, 50, 26);

        jLabel12.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel12.setText("e-mail");
        jLayeredPane1.add(jLabel12);
        jLabel12.setBounds(10, 210, 50, 26);
        jLayeredPane1.add(txtsitio);
        txtsitio.setBounds(80, 250, 250, 20);

        jLabel6.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel6.setText("Descripción");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(140, 320, 80, 26);
        jLayeredPane1.add(txtdes);
        txtdes.setBounds(20, 350, 300, 100);
        jLayeredPane1.add(txtprod);
        txtprod.setBounds(80, 290, 250, 20);
        jLayeredPane1.add(txtdirec);
        txtdirec.setBounds(80, 90, 250, 20);
        jLayeredPane1.add(txtele);
        txtele.setBounds(80, 130, 250, 20);
        jLayeredPane1.add(txtcelular);
        txtcelular.setBounds(80, 170, 250, 20);

        jLabel3.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel3.setText("Producto");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(10, 290, 60, 20);
        jLayeredPane1.add(txte);
        txte.setBounds(80, 210, 250, 20);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 340, 480));

        Tabla_prov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        Tabla_prov.getTableHeader().setResizingAllowed(false);
        Tabla_prov.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla_prov);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 510, 320));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Hora:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Niagara Solid", 1, 18)); // NOI18N
        jLabel13.setText("Fecha");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));
        getContentPane().add(date_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 90, 50));

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoazulceleste_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardaActionPerformed
        if (!camposllenos()) {
            JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS SON OBLIGATORIOS");
            return;
        }
        try {
            Proveedor_Utilidades pu = new Proveedor_Utilidades();
            pu.setRuta("src\\Archivos\\proveedores.txt");
            //List<Medicos> lista = new ArrayList();
            for (Proveedores elem : proveedores) {
                if (txtcode.getText().equals(elem.getCodigo())) {
                    JOptionPane.showMessageDialog(rootPane, "Paciente ya Registrado!!");
                    return;
                }
            }
            Proveedores p = new Proveedores();

            p.setCelular(txtcelular.getText());
            p.setCodigo(txtcode.getText());
            p.setDescripcion(txtdes.getText());
            p.setDireccion(txtdirec.getText());
            p.setEmail(txte.getText());
            p.setEmpresa(txtempresa.getText());
            p.setProducto(txtprod.getText());
            p.setSitioweb(txtsitio.getText());
            p.setTelefono(txtele.getText());
            p.setFecha(String.valueOf(date_fecha.getCalendar().get(Calendar.DAY_OF_MONTH)) + "/" + String.valueOf(date_fecha.getCalendar().get(Calendar.MONTH) + 1) + "/" + String.valueOf(date_fecha.getCalendar().get(Calendar.YEAR)).toString());
            
            proveedores.add(p);
            Proveedor_Utilidades pun = new Proveedor_Utilidades();
            pun.setRuta("src\\Archivos\\proveedores.txt");
            pun.guardarProveedor(proveedores);
            JOptionPane.showMessageDialog(null, "Guardado con éxito!!");
            borrar();
            tabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error");
        }
    }//GEN-LAST:event_guardaActionPerformed

    public Boolean camposllenos() {
        JTextField campos[] = {txtcelular, txtcode, txtdes, txtdirec, txte, txtele, txtempresa, txtprod, txtsitio};
        if (new vld_textbox().camposLlenos(campos)) {
                return true;
        }
        return false;
    }
    
    public void Disable(){
        txtcelular.enable(false);
        txtcode.enable(false);
        txtdes.enable(false);
        txtdirec.enable(false);
        txte.enable(false);
        txtempresa.enable(false);
        txtprod.enable(false);
        txtsitio.enable(false);
        txtele.enable(false);
        date_fecha.enable(false);
    }
    public void borrar(){
        txtcelular.setText("");
        txtcode.setText("");
        txtdes.setText("");
        txtdirec.setText("");
        txte.setText("");
        txtempresa.setText("");
        txtprod.setText("");
        txtsitio.setText("");
        txtele.setText("");
        date_fecha.setDate(new Date());
    }
    
    public static String fechaActual() {
        Date Fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(Fecha);
    }
    
    public void cargarProveedores() {
        File f = new File("src\\Archivos\\proveedores.txt");
        try {

            if (f.exists()) {
                FileInputStream fis = new FileInputStream(f);
                ObjectInputStream ois = new ObjectInputStream(fis);
                proveedores = (ArrayList<Proveedores>) ois.readObject();
                fis.close();
                ois.close();
                System.out.println("archivo cargado");
            } else {
                f.createNewFile();
                System.out.println("archivo creado");
            }
        } catch (Exception e) {
        }
    }
    
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();
        Menu inter = new Menu();
        inter.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarProveedores();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void nuevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevActionPerformed
        txtcelular.enable(true);
        txtcode.enable(true);
        txtdes.enable(true);
        txtdirec.enable(true);
        txte.enable(true);
        txtempresa.enable(true);
        txtprod.enable(true);
        txtsitio.enable(true);
        txtele.enable(true);
        date_fecha.enable(true);       // TODO add your handling code here:
    }//GEN-LAST:event_nuevActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if (!camposllenos()) {
            JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS SON OBLIGATORIOS");
            return;
        }
        try {
            remover:
            for (Proveedores elem : proveedores) {
               
                if (txtcode.getText().trim().equals(elem.getCodigo())) {
                    proveedores.remove(elem);
                    break remover;
                }
            }
        } catch (Exception e) {
        }

        try {
            Proveedores p = new Proveedores();
            p.setCelular(txtcelular.getText());
            p.setCodigo(txtcode.getText());
            p.setDescripcion(txtdes.getText());
            p.setDireccion(txtdirec.getText());
            p.setEmail(txte.getText());
            p.setEmpresa(txtempresa.getText());
            p.setProducto(txtprod.getText());
            p.setSitioweb(txtsitio.getText());
            p.setTelefono(txtele.getText());
            p.setFecha(String.valueOf(date_fecha.getCalendar().get(Calendar.DAY_OF_MONTH)) + "/" + String.valueOf(date_fecha.getCalendar().get(Calendar.MONTH) + 1) + "/" + String.valueOf(date_fecha.getCalendar().get(Calendar.YEAR)).toString());
            
            proveedores.add(p);
            Proveedor_Utilidades pu = new Proveedor_Utilidades();
            pu.setRuta("src\\Archivos\\proveedores.txt");

            pu.guardarProveedor(proveedores);

            JOptionPane.showMessageDialog(null, "Guardado con éxito!!");
            borrar();
            tabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Proveedor_Utilidades pu = new Proveedor_Utilidades();
        pu.setRuta("src\\Archivos\\proveedores.txt");

        for (Proveedores elem : proveedores) {

            if (codigo.equals(elem.getCodigo())) {
                proveedores.remove(elem);
                pu.guardarProveedor(proveedores);

                JOptionPane.showMessageDialog(null, "Eliminado!!");
                borrar();
                tabla();
                return;
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        Boolean confirma = false;
        for (Proveedores elem : proveedores) {
            if (txtcode.getText().equals(elem.getCodigo())) {
                codigo = elem.getCodigo();
                txtcelular.setText(elem.getCelular());
                txtdes.setText(elem.getDescripcion());
                txte.setText(elem.getEmail());
                txtdirec.setText(elem.getDireccion());
                txtele.setText(elem.getTelefono());
                txtempresa.setText(elem.getEmpresa());
                txtprod.setText(elem.getProducto());
                txtsitio.setText(elem.getSitioweb());
                confirma=true;
                //date_fecha.setDate(elem.getFecha_registro());
            } 
        }        // TODO add your handling code here:
        if(!confirma) {
                JOptionPane.showMessageDialog(null, "CEDULA NO REGISTRADA");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    public void tabla() {

        String columnas[] = {"CODIGO", "EMPRESA" , "DIRECCION", "TELEFONO", "CELULAR", "E-MAIL", "SITIO WEB" , "PRODUCTO" , "DESCRIPCION" , "FECHA"};
        DefaultTableModel tm = new DefaultTableModel(null, columnas);

        Proveedor_Utilidades pu = new Proveedor_Utilidades();
        pu.setRuta("src\\Archivos\\proveedores.txt");

        List<Proveedores> lista = new ArrayList();

        try {
            lista = pu.consultarProveedor();

            for (Proveedores elem : lista) {

                String registros[] = {elem.getCodigo(),elem.getEmpresa(),elem.getDireccion(),elem.getTelefono(),elem.getCelular(),elem.getEmail(),elem.getSitioweb(),elem.getProducto(),elem.getDescripcion(),elem.getFecha()};
                tm.addRow(registros);
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "error");
        }

        Tabla_prov.setModel(tm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Proveedor().setVisible(true);
            }
        });
    }
ArrayList<Proveedores> proveedores = new ArrayList<Proveedores>();
String codigo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_prov;
    private javax.swing.JButton buscar;
    private com.toedter.calendar.JDateChooser date_fecha;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guarda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton nuev;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txte;
    private javax.swing.JTextField txtele;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txtprod;
    private javax.swing.JTextField txtsitio;
    // End of variables declaration//GEN-END:variables
}
